2023-08-24 13:32:45,951 INFO    MainThread:12824 [wandb_setup.py:_flush():76] Current SDK version is 0.15.8
2023-08-24 13:32:45,951 INFO    MainThread:12824 [wandb_setup.py:_flush():76] Configure stats pid to 12824
2023-08-24 13:32:45,951 INFO    MainThread:12824 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Huang\.config\wandb\settings
2023-08-24 13:32:45,951 INFO    MainThread:12824 [wandb_setup.py:_flush():76] Loading settings from d:\google drive\MAE Bs PJ\wandb\settings
2023-08-24 13:32:45,951 INFO    MainThread:12824 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-08-24 13:32:45,951 INFO    MainThread:12824 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-08-24 13:32:45,951 INFO    MainThread:12824 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-08-24 13:32:45,951 INFO    MainThread:12824 [wandb_init.py:_log_setup():507] Logging user logs to d:\google drive\MAE Bs PJ\wandb\run-20230824_133245-vhvza41p\logs\debug.log
2023-08-24 13:32:45,951 INFO    MainThread:12824 [wandb_init.py:_log_setup():508] Logging internal logs to d:\google drive\MAE Bs PJ\wandb\run-20230824_133245-vhvza41p\logs\debug-internal.log
2023-08-24 13:32:45,952 INFO    MainThread:12824 [wandb_init.py:init():547] calling init triggers
2023-08-24 13:32:45,952 INFO    MainThread:12824 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-08-24 13:32:45,952 INFO    MainThread:12824 [wandb_init.py:init():596] starting backend
2023-08-24 13:32:45,952 INFO    MainThread:12824 [wandb_init.py:init():600] setting up manager
2023-08-24 13:32:45,955 INFO    MainThread:12824 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-08-24 13:32:45,956 INFO    MainThread:12824 [wandb_init.py:init():606] backend started and connected
2023-08-24 13:32:45,958 INFO    MainThread:12824 [wandb_run.py:_label_probe_notebook():1234] probe notebook
2023-08-24 13:32:45,958 INFO    MainThread:12824 [wandb_run.py:_label_probe_notebook():1244] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-08-24 13:32:45,958 INFO    MainThread:12824 [wandb_init.py:init():697] updated telemetry
2023-08-24 13:32:45,958 INFO    MainThread:12824 [wandb_init.py:init():730] communicating run to backend with 60.0 second timeout
2023-08-24 13:33:46,451 ERROR   MainThread:12824 [wandb_init.py:init():756] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-08-24 13:33:46,505 ERROR   MainThread:12824 [wandb_init.py:init():1165] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "c:\Users\Huang\anaconda3\envs\v11-4\Lib\site-packages\wandb\sdk\wandb_init.py", line 1147, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\Users\Huang\anaconda3\envs\v11-4\Lib\site-packages\wandb\sdk\wandb_init.py", line 762, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-08-24 13:39:05,285 INFO    MainThread:12824 [wandb_setup.py:_flush():76] Current SDK version is 0.15.8
2023-08-24 13:39:05,285 INFO    MainThread:12824 [wandb_setup.py:_flush():76] Configure stats pid to 12824
2023-08-24 13:39:05,285 INFO    MainThread:12824 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Huang\.config\wandb\settings
2023-08-24 13:39:05,285 INFO    MainThread:12824 [wandb_setup.py:_flush():76] Loading settings from d:\google drive\MAE Bs PJ\wandb\settings
2023-08-24 13:39:05,285 INFO    MainThread:12824 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-08-24 13:39:05,285 INFO    MainThread:12824 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-08-24 13:39:05,285 INFO    MainThread:12824 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-08-24 13:39:05,286 INFO    MainThread:12824 [wandb_init.py:_log_setup():507] Logging user logs to d:\google drive\MAE Bs PJ\wandb\run-20230824_133905-h5vnwymv\logs\debug.log
2023-08-24 13:39:05,286 INFO    MainThread:12824 [wandb_init.py:_log_setup():508] Logging internal logs to d:\google drive\MAE Bs PJ\wandb\run-20230824_133905-h5vnwymv\logs\debug-internal.log
2023-08-24 13:39:05,286 INFO    MainThread:12824 [wandb_init.py:init():547] calling init triggers
2023-08-24 13:39:05,286 INFO    MainThread:12824 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-08-24 13:39:05,286 INFO    MainThread:12824 [wandb_init.py:init():596] starting backend
2023-08-24 13:39:05,286 INFO    MainThread:12824 [wandb_init.py:init():600] setting up manager
2023-08-24 13:39:05,288 INFO    MainThread:12824 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-08-24 13:39:05,289 INFO    MainThread:12824 [wandb_init.py:init():606] backend started and connected
2023-08-24 13:39:05,291 INFO    MainThread:12824 [wandb_run.py:_label_probe_notebook():1234] probe notebook
2023-08-24 13:39:05,291 INFO    MainThread:12824 [wandb_run.py:_label_probe_notebook():1244] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-08-24 13:39:05,291 INFO    MainThread:12824 [wandb_init.py:init():697] updated telemetry
2023-08-24 13:39:05,292 INFO    MainThread:12824 [wandb_init.py:init():730] communicating run to backend with 60.0 second timeout
2023-08-24 13:40:05,845 ERROR   MainThread:12824 [wandb_init.py:init():756] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-08-24 13:40:05,898 ERROR   MainThread:12824 [wandb_init.py:init():1165] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "c:\Users\Huang\anaconda3\envs\v11-4\Lib\site-packages\wandb\sdk\wandb_init.py", line 1147, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\Users\Huang\anaconda3\envs\v11-4\Lib\site-packages\wandb\sdk\wandb_init.py", line 762, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
